<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('leases', function (Blueprint $table): void {

            /*
            |--------------------------------------------------------------------------
            | Primary Key
            |--------------------------------------------------------------------------
            */

            $table->id();

            /*
            |--------------------------------------------------------------------------
            | Lease Identification
            |--------------------------------------------------------------------------
            |
            | Example:
            |
            | LSE-000001
            |
            | Generated by Lease::generateLeaseNumber().
            |
            */

            $table->string('lease_number', 50)
                ->unique();

            /*
            |--------------------------------------------------------------------------
            | Tenancy Relationship
            |--------------------------------------------------------------------------
            |
            | Every lease belongs to an existing tenancy.
            |
            | Deleting a tenancy deletes its leases because a lease cannot
            | exist independently from its parent tenancy.
            |
            */

            $table->foreignId('tenancy_id')
                ->constrained('tenancies')
                ->cascadeOnUpdate()
                ->cascadeOnDelete();

            /*
            |--------------------------------------------------------------------------
            | Lease Type
            |--------------------------------------------------------------------------
            |
            | Supported application values:
            |
            | - fixed_term
            | - month_to_month
            | - renewal
            | - short_term
            |
            | Validation is intentionally handled by the application layer.
            |
            */

            $table->string('lease_type', 30)
                ->default('fixed_term')
                ->index();

            /*
            |--------------------------------------------------------------------------
            | Contractual Lease Period
            |--------------------------------------------------------------------------
            |
            | start_date:
            | Date on which the lease begins.
            |
            | end_date:
            | Contractual date on which the lease ends.
            |
            | end_date is nullable to support open-ended agreements such as
            | month-to-month leases.
            |
            */

            $table->date('start_date')
                ->index();

            $table->date('end_date')
                ->nullable()
                ->index();

            /*
            |--------------------------------------------------------------------------
            | Financial Terms
            |--------------------------------------------------------------------------
            |
            | These are the financial terms agreed in the lease.
            |
            | They are intentionally independent from the current pricing of
            | the property, apartment, or unit.
            |
            */

            $table->decimal('rent_amount', 15, 2)
                ->default(0);

            $table->decimal('deposit_amount', 15, 2)
                ->default(0);

            $table->decimal('service_charge', 15, 2)
                ->default(0);

            $table->decimal('late_fee', 15, 2)
                ->default(0);

            /*
            |--------------------------------------------------------------------------
            | Payment Terms
            |--------------------------------------------------------------------------
            |
            | Supported application values:
            |
            | - daily
            | - weekly
            | - monthly
            | - quarterly
            | - semi_annually
            | - annually
            | - one_time
            |
            */

            $table->string('payment_frequency', 30)
                ->default('monthly')
                ->index();

            /*
            | Day of the month on which payment is due.
            |
            | Example:
            |
            | 1 = first day of the month
            |
            */

            $table->unsignedTinyInteger('due_day')
                ->nullable();

            /*
            |--------------------------------------------------------------------------
            | Notice Period
            |--------------------------------------------------------------------------
            |
            | Number of days of notice required before termination.
            |
            */

            $table->unsignedSmallInteger('notice_period_days')
                ->nullable();

            /*
            |--------------------------------------------------------------------------
            | Lease Lifecycle Status
            |--------------------------------------------------------------------------
            |
            | Supported application values:
            |
            | - draft
            | - pending
            | - active
            | - expired
            | - terminated
            | - cancelled
            |
            | IMPORTANT:
            |
            | The database does not automatically change status when end_date
            | passes.
            |
            | Expiration is managed by:
            |
            | Lease::shouldExpire()
            | LeaseService::expireEndedLeases()
            | scheduled expiration command
            |
            | An active lease whose end_date is before today becomes:
            |
            | status = expired
            |
            */

            $table->string('status', 30)
                ->default('draft')
                ->index();

            /*
            |--------------------------------------------------------------------------
            | Signing Information
            |--------------------------------------------------------------------------
            |
            | Date and time when the lease was formally signed.
            |
            */

            $table->dateTime('signed_at')
                ->nullable()
                ->index();

            /*
            |--------------------------------------------------------------------------
            | Termination Information
            |--------------------------------------------------------------------------
            |
            | terminated_at is used for manually terminated leases.
            |
            | Naturally expired leases must NOT populate terminated_at.
            |
            */

            $table->dateTime('terminated_at')
                ->nullable()
                ->index();

            $table->text('termination_reason')
                ->nullable();

            /*
            |--------------------------------------------------------------------------
            | Lease Document
            |--------------------------------------------------------------------------
            |
            | Stores the storage path/reference for the lease document.
            |
            */

            $table->string('document_path', 500)
                ->nullable();

            /*
            |--------------------------------------------------------------------------
            | Notes
            |--------------------------------------------------------------------------
            */

            $table->text('notes')
                ->nullable();

            /*
            |--------------------------------------------------------------------------
            | Timestamps & Soft Deletes
            |--------------------------------------------------------------------------
            |
            | Soft deletes preserve historical lease records and allow
            | administrators to restore accidentally deleted leases.
            |
            */

            $table->timestamps();

            $table->softDeletes();

            /*
            |--------------------------------------------------------------------------
            | Composite Indexes
            |--------------------------------------------------------------------------
            */

            /*
            | Tenancy + Status
            |
            | Supports:
            |
            | - active leases for a tenancy
            | - lease history
            | - expired leases for a tenancy
            |
            */

            $table->index(
                ['tenancy_id', 'status'],
                'leases_tenancy_status_index'
            );

            /*
            | Status + Start Date
            |
            | Supports:
            |
            | - active lease queries
            | - pending/draft queries
            | - upcoming leases
            | - reporting by start date
            |
            */

            $table->index(
                ['status', 'start_date'],
                'leases_status_start_date_index'
            );

            /*
            | Status + End Date
            |
            | CRITICAL FOR EXPIRATION PROCESSING.
            |
            | Supports:
            |
            | WHERE status = 'active'
            | AND end_date < today
            |
            */

            $table->index(
                ['status', 'end_date'],
                'leases_status_end_date_index'
            );

            /*
            | Lease Type + Status
            |
            | Supports lease-type reporting and filtering.
            */

            $table->index(
                ['lease_type', 'status'],
                'leases_type_status_index'
            );

            /*
            | Payment Frequency + Status
            |
            | Supports financial and lease reporting.
            */

            $table->index(
                ['payment_frequency', 'status'],
                'leases_payment_status_index'
            );

            /*
            | End Date + Status
            |
            | Supports date-first reporting and expiration-date queries.
            |
            | Note:
            |
            | This is intentionally retained in addition to
            | (status, end_date) because the two indexes support different
            | query-leading columns.
            */

            $table->index(
                ['end_date', 'status'],
                'leases_end_date_status_index'
            );
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('leases');
    }
};
