<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('payment_refunds', function (Blueprint $table) {
            /*
            |--------------------------------------------------------------------------
            | Primary Key
            |--------------------------------------------------------------------------
            */

            $table->id();

            /*
            |--------------------------------------------------------------------------
            | Payment Relationship
            |--------------------------------------------------------------------------
            |
            | Every refund belongs to an original payment.
            |
            | The original payment is retained as part of the financial
            | history. Deleting a payment should therefore also remove its
            | dependent refund records.
            |
            */

            $table->foreignId('payment_id')
                ->constrained('payments')
                ->cascadeOnDelete();

            /*
            |--------------------------------------------------------------------------
            | Refund Identification
            |--------------------------------------------------------------------------
            |
            | Internal refund number generated by the PaymentRefund model.
            |
            | Example:
            |
            | REF-20260905-482731
            |
            */

            $table->string('refund_number', 50)
                ->unique();

            /*
            |--------------------------------------------------------------------------
            | Refund Amount
            |--------------------------------------------------------------------------
            |
            | Amount returned to the customer.
            |
            | This may be less than or equal to the original payment amount.
            |
            */

            $table->decimal('amount', 15, 2);

            /*
            |--------------------------------------------------------------------------
            | Currency
            |--------------------------------------------------------------------------
            |
            | ISO 4217 currency code.
            |
            | Example:
            |
            | KES
            |
            */

            $table->char('currency', 3)
                ->default('KES');

            /*
            |--------------------------------------------------------------------------
            | Refund Method
            |--------------------------------------------------------------------------
            |
            | Supported methods:
            |
            | - mpesa
            | - bank_transfer
            | - cash
            | - card
            | - other
            |
            */

            $table->string('refund_method', 50)
                ->nullable();

            /*
            |--------------------------------------------------------------------------
            | Refund Status
            |--------------------------------------------------------------------------
            |
            | Supported statuses:
            |
            | - pending
            | - completed
            | - failed
            | - cancelled
            |
            */

            $table->string('status', 30)
                ->default('pending');

            /*
            |--------------------------------------------------------------------------
            | Refund Reference
            |--------------------------------------------------------------------------
            |
            | External reference returned by the refund provider.
            |
            | Examples:
            |
            | - M-Pesa refund reference
            | - Bank refund reference
            | - Card refund reference
            | - Internal transaction reference
            |
            */

            $table->string('refund_reference', 150)
                ->nullable()
                ->unique();

            /*
            |--------------------------------------------------------------------------
            | Refund Dates
            |--------------------------------------------------------------------------
            |
            | refund_date:
            | Accounting/business date of the refund.
            |
            | refunded_at:
            | Exact timestamp when the refund was successfully processed.
            |
            */

            $table->date('refund_date')
                ->nullable();

            $table->timestamp('refunded_at')
                ->nullable();

            /*
            |--------------------------------------------------------------------------
            | Refund Reason
            |--------------------------------------------------------------------------
            |
            | Reason why the payment or portion of the payment was refunded.
            |
            */

            $table->text('reason')
                ->nullable();

            /*
            |--------------------------------------------------------------------------
            | Additional Notes
            |--------------------------------------------------------------------------
            */

            $table->text('notes')
                ->nullable();

            /*
            |--------------------------------------------------------------------------
            | Audit Information
            |--------------------------------------------------------------------------
            |
            | created_by:
            | User who initiated or recorded the refund.
            |
            | updated_by:
            | User who last modified the refund record.
            |
            | Both remain nullable to support system-generated refunds.
            |
            */

            $table->foreignId('created_by')
                ->nullable()
                ->constrained('users')
                ->nullOnDelete();

            $table->foreignId('updated_by')
                ->nullable()
                ->constrained('users')
                ->nullOnDelete();

            /*
            |--------------------------------------------------------------------------
            | Timestamps
            |--------------------------------------------------------------------------
            */

            $table->timestamps();

            /*
            |--------------------------------------------------------------------------
            | Relationship Indexes
            |--------------------------------------------------------------------------
            */

            $table->index(
                'payment_id',
                'payment_refunds_payment_id_index'
            );

            $table->index(
                'created_by',
                'payment_refunds_created_by_index'
            );

            $table->index(
                'updated_by',
                'payment_refunds_updated_by_index'
            );

            /*
            |--------------------------------------------------------------------------
            | Status / Reporting Indexes
            |--------------------------------------------------------------------------
            */

            $table->index(
                ['status', 'refund_date'],
                'payment_refunds_status_date_index'
            );

            $table->index(
                ['refund_method', 'status'],
                'payment_refunds_method_status_index'
            );

            $table->index(
                ['payment_id', 'status'],
                'payment_refunds_payment_status_index'
            );

            $table->index(
                ['currency', 'status'],
                'payment_refunds_currency_status_index'
            );

            /*
            |--------------------------------------------------------------------------
            | Completion Reporting Index
            |--------------------------------------------------------------------------
            */

            $table->index(
                ['refunded_at', 'status'],
                'payment_refunds_refunded_at_status_index'
            );
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('payment_refunds');
    }
};