<?php

namespace Database\Seeders;

use App\Models\Plot;
use App\Models\PlotSale;
use App\Models\User;
use Illuminate\Database\Seeder;

class PlotSaleSeeder extends Seeder
{
    /**
     * Seed plot sales.
     */
    public function run(): void
    {
        /*
        |--------------------------------------------------------------------------
        | LOAD ALL PLOTS
        |--------------------------------------------------------------------------
        |
        | Plot codes are dynamically generated by PlotSeeder.
        |
        | Therefore, this seeder uses plot_number as the stable identifier
        | instead of depending on generated plot codes.
        |
        */

        $plots = Plot::query()
            ->whereIn('plot_number', [
                'RUIRU/1/1287',
                'KITENGELA/2/4521',
                'SYOKIMAU/3/3421',
                'JUJA/4/5632',
                'NGONG/5/7843',
                'ATHI RIVER/6/2198',
                'RUAKA/7/7846',
                'KAREN/8/9135',
            ])
            ->get()
            ->keyBy('plot_number');

        /*
        |--------------------------------------------------------------------------
        | FALLBACK
        |--------------------------------------------------------------------------
        |
        | If the exact plot numbers above are different from the values in
        | your current PlotSeeder, load the first eight plots instead.
        |
        */

        if ($plots->count() < 8) {
            $this->command?->warn(
                'Some expected plot numbers were not found. Loading the first 8 plots instead.'
            );

            $plots = Plot::query()
                ->orderBy('id')
                ->limit(8)
                ->get();
        }

        /*
        |--------------------------------------------------------------------------
        | VALIDATE PLOTS
        |--------------------------------------------------------------------------
        */

        if ($plots->count() < 8) {
            $this->command?->warn(
                'PlotSaleSeeder skipped: at least 8 plots are required.'
            );

            $this->command?->warn(
                'Run PlotSeeder before PlotSaleSeeder.'
            );

            return;
        }

        /*
        |--------------------------------------------------------------------------
        | BUYERS
        |--------------------------------------------------------------------------
        |
        | Prefer users with the tenant role.
        |
        | If tenant users are unavailable, use existing users as buyers.
        |
        */

        $buyers = User::query()
            ->role('tenant')
            ->orderBy('id')
            ->get();

        if ($buyers->isEmpty()) {
            $this->command?->warn(
                'No users with tenant role found. Using available users as buyers.'
            );

            $buyers = User::query()
                ->orderBy('id')
                ->get();
        }

        /*
        |--------------------------------------------------------------------------
        | VALIDATE BUYERS
        |--------------------------------------------------------------------------
        */

        if ($buyers->isEmpty()) {
            $this->command?->warn(
                'PlotSaleSeeder skipped: no users are available as buyers.'
            );

            return;
        }

        /*
        |--------------------------------------------------------------------------
        | AGENTS
        |--------------------------------------------------------------------------
        */

        $agents = User::query()
            ->role('agent')
            ->orderBy('id')
            ->get();

        /*
        |--------------------------------------------------------------------------
        | PREPARE BUYERS
        |--------------------------------------------------------------------------
        |
        | Reuse buyers when there are fewer buyers than plots.
        |
        */

        $buyerCount = $buyers->count();

        /*
        |--------------------------------------------------------------------------
        | PREPARE AGENTS
        |--------------------------------------------------------------------------
        */

        $agentCount = $agents->count();

        /*
        |--------------------------------------------------------------------------
        | SALES DATA
        |--------------------------------------------------------------------------
        |
        | Eight plots = eight plot sales.
        |
        | Status distribution:
        |
        | 1. Pending
        | 2. Approved
        | 3. Reserved
        | 4. Completed
        | 5. Pending
        | 6. Approved
        | 7. Completed
        | 8. Cancelled
        |
        */

        $sales = [
            [
                'plot_number' => 'RUIRU/1/1287',
                'sale_price' => 3500000,
                'deposit_amount' => 500000,
                'discount_amount' => 0,
                'amount_paid' => 500000,
                'payment_frequency' => 'monthly',
                'status' => 'pending',
                'sale_date' => now()->toDateString(),
                'due_date' => now()->addMonth()->toDateString(),
                'completion_date' => null,
                'notes' => 'Buyer has submitted an offer and the sale is awaiting approval.',
            ],

            [
                'plot_number' => 'KITENGELA/2/4521',
                'sale_price' => 2800000,
                'deposit_amount' => 700000,
                'discount_amount' => 100000,
                'amount_paid' => 700000,
                'payment_frequency' => 'monthly',
                'status' => 'approved',
                'sale_date' => now()->subDays(5)->toDateString(),
                'due_date' => now()->addMonth()->toDateString(),
                'completion_date' => null,
                'notes' => 'Plot sale approved and awaiting completion of the agreed payment plan.',
            ],

            [
                'plot_number' => 'SYOKIMAU/3/3421',
                'sale_price' => 4200000,
                'deposit_amount' => 1000000,
                'discount_amount' => 200000,
                'amount_paid' => 1000000,
                'payment_frequency' => 'monthly',
                'status' => 'reserved',
                'sale_date' => now()->subDays(10)->toDateString(),
                'due_date' => now()->addMonth()->toDateString(),
                'completion_date' => null,
                'notes' => 'Plot reserved pending completion of the agreed payment plan.',
            ],

            [
                'plot_number' => 'JUJA/4/5632',
                'sale_price' => 8500000,
                'deposit_amount' => 2000000,
                'discount_amount' => 500000,
                'amount_paid' => 8000000,
                'payment_frequency' => 'once',
                'status' => 'completed',
                'sale_date' => now()->subMonths(3)->toDateString(),
                'due_date' => now()->subMonths(2)->toDateString(),
                'completion_date' => now()->subMonths(2)->addDays(10)->toDateString(),
                'notes' => 'Commercial plot sale completed after full settlement and documentation.',
            ],

            [
                'plot_number' => 'NGONG/5/7843',
                'sale_price' => 3200000,
                'deposit_amount' => 400000,
                'discount_amount' => 0,
                'amount_paid' => 400000,
                'payment_frequency' => 'monthly',
                'status' => 'pending',
                'sale_date' => now()->subDays(3)->toDateString(),
                'due_date' => now()->addMonth()->toDateString(),
                'completion_date' => null,
                'notes' => 'Residential plot sale awaiting confirmation and approval.',
            ],

            [
                'plot_number' => 'ATHI RIVER/6/2198',
                'sale_price' => 12500000,
                'deposit_amount' => 2500000,
                'discount_amount' => 500000,
                'amount_paid' => 2500000,
                'payment_frequency' => 'quarterly',
                'status' => 'approved',
                'sale_date' => now()->subDays(14)->toDateString(),
                'due_date' => now()->addMonths(3)->toDateString(),
                'completion_date' => null,
                'notes' => 'Development plot sale approved under a quarterly payment plan.',
            ],

            [
                'plot_number' => 'RUAKA/7/7846',
                'sale_price' => 9800000,
                'deposit_amount' => 2000000,
                'discount_amount' => 300000,
                'amount_paid' => 9500000,
                'payment_frequency' => 'once',
                'status' => 'completed',
                'sale_date' => now()->subMonths(2)->toDateString(),
                'due_date' => now()->subMonth()->toDateString(),
                'completion_date' => now()->subDays(15)->toDateString(),
                'notes' => 'Premium plot sale completed after full settlement and completion of documentation.',
            ],

            [
                'plot_number' => 'KAREN/8/9135',
                'sale_price' => 18000000,
                'deposit_amount' => 1000000,
                'discount_amount' => 500000,
                'amount_paid' => 1000000,
                'payment_frequency' => 'monthly',
                'status' => 'cancelled',
                'sale_date' => now()->subMonth()->toDateString(),
                'due_date' => now()->subDays(10)->toDateString(),
                'completion_date' => null,
                'notes' => 'Sale cancelled after the buyer withdrew from the transaction.',
            ],
        ];

        /*
        |--------------------------------------------------------------------------
        | CREATE / UPDATE SALES
        |--------------------------------------------------------------------------
        */

        foreach ($sales as $index => $saleData) {

            /*
            |--------------------------------------------------------------------------
            | FIND PLOT
            |--------------------------------------------------------------------------
            */

            $plot = $plots->firstWhere(
                'plot_number',
                $saleData['plot_number']
            );

            /*
            |--------------------------------------------------------------------------
            | SKIP MISSING PLOT
            |--------------------------------------------------------------------------
            */

            if (!$plot) {
                $this->command?->warn(
                    "Plot not found: {$saleData['plot_number']}"
                );

                continue;
            }

            /*
            |--------------------------------------------------------------------------
            | ASSIGN BUYER
            |--------------------------------------------------------------------------
            */

            $buyer = $buyers->get(
                $index % $buyerCount
            );

            /*
            |--------------------------------------------------------------------------
            | ASSIGN AGENT
            |--------------------------------------------------------------------------
            */

            $agent = $agentCount > 0
                ? $agents->get($index % $agentCount)
                : null;

            /*
            |--------------------------------------------------------------------------
            | FINANCIAL CALCULATION
            |--------------------------------------------------------------------------
            */

            $salePrice = (float) $saleData['sale_price'];

            $discount = (float) $saleData['discount_amount'];

            $amountPaid = (float) $saleData['amount_paid'];

            /*
            |--------------------------------------------------------------------------
            | NET SALE PRICE
            |--------------------------------------------------------------------------
            */

            $netSalePrice = max(
                0,
                $salePrice - $discount
            );

            /*
            |--------------------------------------------------------------------------
            | BALANCE
            |--------------------------------------------------------------------------
            */

            $balance = max(
                0,
                $netSalePrice - $amountPaid
            );

            /*
            |--------------------------------------------------------------------------
            | SALE NUMBER
            |--------------------------------------------------------------------------
            */

            $saleNumber = sprintf(
                'PS-20261005-%06d',
                $index + 1
            );

            /*
            |--------------------------------------------------------------------------
            | CREATE / UPDATE SALE
            |--------------------------------------------------------------------------
            */

            PlotSale::updateOrCreate(
                [
                    'sale_number' => $saleNumber,
                ],
                [
                    'plot_id' => $plot->id,

                    'buyer_id' => $buyer->id,

                    'agent_id' => $agent?->id,

                    'sale_date' => $saleData['sale_date'],

                    'sale_price' => $salePrice,

                    'deposit_amount' => $saleData['deposit_amount'],

                    'discount_amount' => $discount,

                    'amount_paid' => $amountPaid,

                    'balance' => $balance,

                    'currency' => 'KES',

                    'payment_frequency' => $saleData['payment_frequency'],

                    'due_date' => $saleData['due_date'],

                    'completion_date' => $saleData['completion_date'],

                    'notes' => $saleData['notes'],

                    'status' => $saleData['status'],

                    'is_active' => !in_array(
                        $saleData['status'],
                        ['cancelled']
                    ),
                ]
            );

            /*
            |--------------------------------------------------------------------------
            | UPDATE PLOT STATUS
            |--------------------------------------------------------------------------
            */

            $plotStatus = match ($saleData['status']) {

                'pending' => 'available',

                'approved' => 'reserved',

                'reserved' => 'reserved',

                'completed' => 'sold',

                'cancelled' => 'available',

                default => 'available',
            };

            /*
            |--------------------------------------------------------------------------
            | UPDATE PLOT ACTIVE STATUS
            |--------------------------------------------------------------------------
            */

            $plot->update([
                'status' => $plotStatus,

                'is_active' => !in_array(
                    $plotStatus,
                    ['sold', 'withdrawn']
                ),
            ]);

            /*
            |--------------------------------------------------------------------------
            | OUTPUT
            |--------------------------------------------------------------------------
            */

            $this->command?->line(
                "Sale {$saleNumber} created for {$plot->title}."
            );
        }

        /*
        |--------------------------------------------------------------------------
        | SUMMARY
        |--------------------------------------------------------------------------
        */

        $saleCount = PlotSale::query()
            ->count();

        $this->command?->newLine();

        $this->command?->info(
            'PlotSaleSeeder completed successfully.'
        );

        $this->command?->info(
            "Plot sales in database: {$saleCount}"
        );

        /*
        |--------------------------------------------------------------------------
        | STATUS SUMMARY
        |--------------------------------------------------------------------------
        */

        $statuses = PlotSale::query()
            ->selectRaw('status, COUNT(*) as total')
            ->groupBy('status')
            ->pluck('total', 'status');

        foreach ($statuses as $status => $total) {
            $this->command?->line(
                ucfirst($status) . ': ' . $total
            );
        }
    }
}

