<?php

namespace App\Http\Requests\Lease;

use App\Models\Lease;
use Carbon\Carbon;
use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class UpdateLeaseRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Prepare the data for validation.
     */
    protected function prepareForValidation(): void
    {
        $this->merge([
            /*
            |--------------------------------------------------------------------------
            | Lease Configuration
            |--------------------------------------------------------------------------
            */

            'lease_type' => $this->filled('lease_type')
                ? strtolower(trim((string) $this->input('lease_type')))
                : null,

            'payment_frequency' => $this->filled('payment_frequency')
                ? strtolower(trim((string) $this->input('payment_frequency')))
                : null,

            'status' => $this->filled('status')
                ? strtolower(trim((string) $this->input('status')))
                : null,

            /*
            |--------------------------------------------------------------------------
            | Dates
            |--------------------------------------------------------------------------
            */

            'start_date' => $this->filled('start_date')
                ? trim((string) $this->input('start_date'))
                : null,

            'end_date' => $this->filled('end_date')
                ? trim((string) $this->input('end_date'))
                : null,

            /*
            |--------------------------------------------------------------------------
            | Termination
            |--------------------------------------------------------------------------
            */

            'termination_reason' => $this->filled('termination_reason')
                ? trim((string) $this->input('termination_reason'))
                : null,

            /*
            |--------------------------------------------------------------------------
            | Documents / Notes
            |--------------------------------------------------------------------------
            */

            'document_path' => $this->filled('document_path')
                ? trim((string) $this->input('document_path'))
                : null,

            'notes' => $this->filled('notes')
                ? trim((string) $this->input('notes'))
                : null,
        ]);
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            /*
            |--------------------------------------------------------------------------
            | Protected Lease Relationship
            |--------------------------------------------------------------------------
            |
            | The tenancy cannot be changed through a normal lease update.
            | Tenant/property/apartment/unit information is resolved through
            | the tenancy relationship.
            |
            */

            'tenancy_id' => [
                'prohibited',
            ],

            /*
            |--------------------------------------------------------------------------
            | Protected System Field
            |--------------------------------------------------------------------------
            |
            | Lease numbers are generated by the application and cannot be
            | changed manually.
            |
            */

            'lease_number' => [
                'prohibited',
            ],

            /*
            |--------------------------------------------------------------------------
            | Lease Type
            |--------------------------------------------------------------------------
            */

            'lease_type' => [
                'sometimes',
                'nullable',
                'string',
                'max:30',
                Rule::in(Lease::LEASE_TYPES),
            ],

            /*
            |--------------------------------------------------------------------------
            | Lease Dates
            |--------------------------------------------------------------------------
            |
            | Both dates remain optional during a PATCH/PUT update.
            |
            | Date relationship is checked in withValidator() so that the
            | existing lease date can be used when only one date is supplied.
            |
            */

            'start_date' => [
                'sometimes',
                'nullable',
                'date',
            ],

            'end_date' => [
                'sometimes',
                'nullable',
                'date',
            ],

            /*
            |--------------------------------------------------------------------------
            | Financial Terms
            |--------------------------------------------------------------------------
            */

            'rent_amount' => [
                'sometimes',
                'numeric',
                'min:0',
                'decimal:0,2',
            ],

            'deposit_amount' => [
                'sometimes',
                'numeric',
                'min:0',
                'decimal:0,2',
            ],

            'service_charge' => [
                'sometimes',
                'nullable',
                'numeric',
                'min:0',
                'decimal:0,2',
            ],

            'late_fee' => [
                'sometimes',
                'nullable',
                'numeric',
                'min:0',
                'decimal:0,2',
            ],

            /*
            |--------------------------------------------------------------------------
            | Payment Terms
            |--------------------------------------------------------------------------
            */

            'payment_frequency' => [
                'sometimes',
                'nullable',
                'string',
                'max:30',
                Rule::in([
                    'daily',
                    'weekly',
                    'monthly',
                    'quarterly',
                    'semi_annually',
                    'annually',
                    'one_time',
                ]),
            ],

            'due_day' => [
                'sometimes',
                'nullable',
                'integer',
                'between:1,31',
            ],

            'notice_period_days' => [
                'sometimes',
                'nullable',
                'integer',
                'min:0',
                'max:365',
            ],

            /*
            |--------------------------------------------------------------------------
            | Lease Status
            |--------------------------------------------------------------------------
            |
            | Status changes should normally be handled through the dedicated
            | lifecycle endpoints:
            |
            | activate
            | pending
            | draft
            | expire
            | terminate
            | cancel
            |
            | The service layer remains responsible for enforcing lifecycle
            | transitions even when status is supplied here.
            |
            */

            'status' => [
                'sometimes',
                'string',
                'max:30',
                Rule::in(Lease::STATUSES),
            ],

            /*
            |--------------------------------------------------------------------------
            | Signature
            |--------------------------------------------------------------------------
            */

            'signed_at' => [
                'sometimes',
                'nullable',
                'date',
            ],

            /*
            |--------------------------------------------------------------------------
            | Termination
            |--------------------------------------------------------------------------
            */

            'terminated_at' => [
                'sometimes',
                'nullable',
                'date',
            ],

            'termination_reason' => [
                'sometimes',
                'nullable',
                'string',
                'max:5000',
            ],

            /*
            |--------------------------------------------------------------------------
            | Documents
            |--------------------------------------------------------------------------
            */

            'document_path' => [
                'sometimes',
                'nullable',
                'string',
                'max:500',
            ],

            /*
            |--------------------------------------------------------------------------
            | Notes
            |--------------------------------------------------------------------------
            */

            'notes' => [
                'sometimes',
                'nullable',
                'string',
                'max:10000',
            ],
        ];
    }

    /**
     * Configure additional validation after the standard rules.
     */
    public function withValidator($validator): void
    {
        $validator->after(function ($validator): void {
            /*
            |--------------------------------------------------------------------------
            | Resolve Existing Lease
            |--------------------------------------------------------------------------
            |
            | The route should normally be:
            |
            | PUT/PATCH /api/leases/{lease}
            |
            | We use route('lease') first and fall back to route('id') to
            | support either route naming convention.
            |
            */

            $lease = $this->route('lease') ?? $this->route('id');

            if (!$lease instanceof Lease) {
                return;
            }

            /*
            |--------------------------------------------------------------------------
            | Resolve Effective Dates
            |--------------------------------------------------------------------------
            |
            | If a date is not included in the request, use the existing
            | database value.
            |
            */

            $effectiveStartDate = $this->exists('start_date')
                ? $this->input('start_date')
                : $lease->start_date;

            $effectiveEndDate = $this->exists('end_date')
                ? $this->input('end_date')
                : $lease->end_date;

            /*
            |--------------------------------------------------------------------------
            | Validate Date Range
            |--------------------------------------------------------------------------
            */

            if (
                filled($effectiveStartDate) &&
                filled($effectiveEndDate)
            ) {
                try {
                    $startDate = Carbon::parse($effectiveStartDate)
                        ->startOfDay();

                    $endDate = Carbon::parse($effectiveEndDate)
                        ->startOfDay();

                    if ($endDate->lt($startDate)) {
                        $validator->errors()->add(
                            'end_date',
                            'The lease end date must be on or after the start date.'
                        );
                    }
                } catch (\Throwable) {
                    /*
                     * The standard date validation rules handle invalid
                     * date formats.
                     */
                }
            }

            /*
            |--------------------------------------------------------------------------
            | Fixed-Term Lease Validation
            |--------------------------------------------------------------------------
            |
            | If the lease is or becomes fixed-term, it must have an end date.
            |
            */

            $effectiveLeaseType = $this->filled('lease_type')
                ? $this->input('lease_type')
                : $lease->lease_type;

            if (
                $effectiveLeaseType === Lease::TYPE_FIXED_TERM &&
                blank($effectiveEndDate)
            ) {
                $validator->errors()->add(
                    'end_date',
                    'The end date is required for a fixed-term lease.'
                );
            }

            /*
            |--------------------------------------------------------------------------
            | Active Lease Validation
            |--------------------------------------------------------------------------
            |
            | An active lease cannot be changed to an end date that has
            | already passed.
            |
            | An end date equal to today is still valid. The lease expires
            | automatically from the following day.
            |
            */

            $effectiveStatus = $this->filled('status')
                ? $this->input('status')
                : $lease->status;

            if (
                $effectiveStatus === Lease::STATUS_ACTIVE &&
                filled($effectiveEndDate)
            ) {
                try {
                    $endDate = Carbon::parse($effectiveEndDate)
                        ->startOfDay();

                    if ($endDate->lt(today())) {
                        $validator->errors()->add(
                            'end_date',
                            'An active lease cannot have an end date in the past.'
                        );
                    }
                } catch (\Throwable) {
                    // Standard date validation handles invalid dates.
                }
            }

            /*
            |--------------------------------------------------------------------------
            | Expired Lease Validation
            |--------------------------------------------------------------------------
            |
            | A lease can only be explicitly changed to expired when its
            | end date has already passed.
            |
            */

            if (
                $effectiveStatus === Lease::STATUS_EXPIRED &&
                filled($effectiveEndDate)
            ) {
                try {
                    $endDate = Carbon::parse($effectiveEndDate)
                        ->startOfDay();

                    if ($endDate->gte(today())) {
                        $validator->errors()->add(
                            'status',
                            'A lease can only be marked as expired after its end date has passed.'
                        );
                    }
                } catch (\Throwable) {
                    // Standard date validation handles invalid dates.
                }
            }

            /*
            |--------------------------------------------------------------------------
            | Termination Validation
            |--------------------------------------------------------------------------
            */

            if (
                $effectiveStatus === Lease::STATUS_TERMINATED &&
                blank($this->input('termination_reason')) &&
                blank($lease->termination_reason)
            ) {
                $validator->errors()->add(
                    'termination_reason',
                    'A termination reason is required when terminating a lease.'
                );
            }

            /*
            |--------------------------------------------------------------------------
            | Cancellation Validation
            |--------------------------------------------------------------------------
            */

            if (
                $effectiveStatus === Lease::STATUS_CANCELLED &&
                blank($this->input('termination_reason')) &&
                blank($lease->termination_reason)
            ) {
                $validator->errors()->add(
                    'termination_reason',
                    'A cancellation reason is required when cancelling a lease.'
                );
            }
        });
    }

    /**
     * Custom validation messages.
     *
     * @return array<string, string>
     */
    public function messages(): array
    {
        return [
            /*
            |--------------------------------------------------------------------------
            | Protected Fields
            |--------------------------------------------------------------------------
            */

            'tenancy_id.prohibited' =>
                'The tenancy cannot be changed during a lease update.',

            'lease_number.prohibited' =>
                'The lease number cannot be changed during a lease update.',

            /*
            |--------------------------------------------------------------------------
            | Lease Type
            |--------------------------------------------------------------------------
            */

            'lease_type.in' =>
                'The selected lease type is invalid.',

            /*
            |--------------------------------------------------------------------------
            | Dates
            |--------------------------------------------------------------------------
            */

            'start_date.date' =>
                'The lease start date must be a valid date.',

            'end_date.date' =>
                'The lease end date must be a valid date.',

            /*
            |--------------------------------------------------------------------------
            | Financial Terms
            |--------------------------------------------------------------------------
            */

            'rent_amount.numeric' =>
                'The rent amount must be a valid number.',

            'rent_amount.min' =>
                'The rent amount cannot be negative.',

            'rent_amount.decimal' =>
                'The rent amount may contain a maximum of two decimal places.',

            'deposit_amount.numeric' =>
                'The deposit amount must be a valid number.',

            'deposit_amount.min' =>
                'The deposit amount cannot be negative.',

            'deposit_amount.decimal' =>
                'The deposit amount may contain a maximum of two decimal places.',

            'service_charge.numeric' =>
                'The service charge must be a valid number.',

            'service_charge.min' =>
                'The service charge cannot be negative.',

            'service_charge.decimal' =>
                'The service charge may contain a maximum of two decimal places.',

            'late_fee.numeric' =>
                'The late fee must be a valid number.',

            'late_fee.min' =>
                'The late fee cannot be negative.',

            'late_fee.decimal' =>
                'The late fee may contain a maximum of two decimal places.',

            /*
            |--------------------------------------------------------------------------
            | Payment Terms
            |--------------------------------------------------------------------------
            */

            'payment_frequency.in' =>
                'The selected payment frequency is invalid.',

            'due_day.integer' =>
                'The due day must be a valid number.',

            'due_day.between' =>
                'The due day must be between 1 and 31.',

            'notice_period_days.integer' =>
                'The notice period must be a valid number.',

            'notice_period_days.min' =>
                'The notice period cannot be negative.',

            'notice_period_days.max' =>
                'The notice period cannot exceed 365 days.',

            /*
            |--------------------------------------------------------------------------
            | Status
            |--------------------------------------------------------------------------
            */

            'status.in' =>
                'The selected lease status is invalid.',

            /*
            |--------------------------------------------------------------------------
            | Signature
            |--------------------------------------------------------------------------
            */

            'signed_at.date' =>
                'The signed date must be a valid date.',

            /*
            |--------------------------------------------------------------------------
            | Termination
            |--------------------------------------------------------------------------
            */

            'terminated_at.date' =>
                'The termination date must be a valid date.',

            'termination_reason.string' =>
                'The termination reason must be valid text.',

            'termination_reason.max' =>
                'The termination reason cannot exceed 5,000 characters.',

            /*
            |--------------------------------------------------------------------------
            | Documents
            |--------------------------------------------------------------------------
            */

            'document_path.string' =>
                'The document path must be valid text.',

            'document_path.max' =>
                'The document path cannot exceed 500 characters.',

            /*
            |--------------------------------------------------------------------------
            | Notes
            |--------------------------------------------------------------------------
            */

            'notes.string' =>
                'The notes must be valid text.',

            'notes.max' =>
                'The notes cannot exceed 10,000 characters.',
        ];
    }

    /**
     * Get validated data prepared for the application layer.
     *
     * @return array<string, mixed>
     */
    public function validatedData(): array
    {
        return $this->validated();
    }
}

