<?php

namespace App\Http\Requests\Lease;

use App\Models\Lease;
use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class UpdateLeaseRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Prepare the data for validation.
     */
    protected function prepareForValidation(): void
    {
        $this->merge([
            'lease_type' => $this->filled('lease_type')
                ? strtolower(trim((string) $this->input('lease_type')))
                : null,

            'payment_frequency' => $this->filled('payment_frequency')
                ? strtolower(trim((string) $this->input('payment_frequency')))
                : null,

            'status' => $this->filled('status')
                ? strtolower(trim((string) $this->input('status')))
                : null,

            'termination_reason' => $this->filled('termination_reason')
                ? trim((string) $this->input('termination_reason'))
                : null,

            'document_path' => $this->filled('document_path')
                ? trim((string) $this->input('document_path'))
                : null,

            'notes' => $this->filled('notes')
                ? trim((string) $this->input('notes'))
                : null,
        ]);
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            /*
            |--------------------------------------------------------------------------
            | Protected Lease Relationship
            |--------------------------------------------------------------------------
            |
            | A lease belongs to one tenancy.
            |
            | The tenancy relationship should not be changed during a normal
            | lease update. Tenant, property, apartment and unit information
            | is resolved through the tenancy relationship.
            |
            */

            'tenancy_id' => [
                'prohibited',
            ],

            /*
            |--------------------------------------------------------------------------
            | Protected System Field
            |--------------------------------------------------------------------------
            |
            | lease_number is generated by the Lease model and must not be
            | changed manually through the update endpoint.
            |
            */

            'lease_number' => [
                'prohibited',
            ],

            /*
            |--------------------------------------------------------------------------
            | Lease Type
            |--------------------------------------------------------------------------
            */

            'lease_type' => [
                'sometimes',
                'nullable',
                'string',
                'max:30',
                Rule::in(Lease::LEASE_TYPES),
            ],

            /*
            |--------------------------------------------------------------------------
            | Lease Dates
            |--------------------------------------------------------------------------
            */

            'start_date' => [
                'sometimes',
                'date',
            ],

            'end_date' => [
                'sometimes',
                'nullable',
                'date',
                'after_or_equal:start_date',
            ],

            /*
            |--------------------------------------------------------------------------
            | Financial Terms
            |--------------------------------------------------------------------------
            */

            'rent_amount' => [
                'sometimes',
                'numeric',
                'min:0',
                'decimal:0,2',
            ],

            'deposit_amount' => [
                'sometimes',
                'numeric',
                'min:0',
                'decimal:0,2',
            ],

            'service_charge' => [
                'sometimes',
                'nullable',
                'numeric',
                'min:0',
                'decimal:0,2',
            ],

            'late_fee' => [
                'sometimes',
                'nullable',
                'numeric',
                'min:0',
                'decimal:0,2',
            ],

            /*
            |--------------------------------------------------------------------------
            | Payment Terms
            |--------------------------------------------------------------------------
            */

            'payment_frequency' => [
                'sometimes',
                'nullable',
                'string',
                'max:30',
                Rule::in([
                    'daily',
                    'weekly',
                    'monthly',
                    'quarterly',
                    'semi_annually',
                    'annually',
                    'one_time',
                ]),
            ],

            'due_day' => [
                'sometimes',
                'nullable',
                'integer',
                'between:1,31',
            ],

            'notice_period_days' => [
                'sometimes',
                'nullable',
                'integer',
                'min:0',
                'max:365',
            ],

            /*
            |--------------------------------------------------------------------------
            | Lease Status
            |--------------------------------------------------------------------------
            */

            'status' => [
                'sometimes',
                'string',
                'max:30',
                Rule::in(Lease::STATUSES),
            ],

            /*
            |--------------------------------------------------------------------------
            | Signature
            |--------------------------------------------------------------------------
            */

            'signed_at' => [
                'sometimes',
                'nullable',
                'date',
            ],

            /*
            |--------------------------------------------------------------------------
            | Termination
            |--------------------------------------------------------------------------
            */

            'terminated_at' => [
                'sometimes',
                'nullable',
                'date',
                'after_or_equal:start_date',
            ],

            'termination_reason' => [
                'sometimes',
                'nullable',
                'string',
                'max:5000',
            ],

            /*
            |--------------------------------------------------------------------------
            | Documents / Notes
            |--------------------------------------------------------------------------
            */

            'document_path' => [
                'sometimes',
                'nullable',
                'string',
                'max:500',
            ],

            'notes' => [
                'sometimes',
                'nullable',
                'string',
                'max:10000',
            ],
        ];
    }

    /**
     * Custom validation messages.
     *
     * @return array<string, string>
     */
    public function messages(): array
    {
        return [
            /*
            |--------------------------------------------------------------------------
            | Protected Fields
            |--------------------------------------------------------------------------
            */

            'tenancy_id.prohibited' =>
                'The tenancy cannot be changed during a lease update.',

            'lease_number.prohibited' =>
                'The lease number cannot be changed during a lease update.',

            /*
            |--------------------------------------------------------------------------
            | Lease Type
            |--------------------------------------------------------------------------
            */

            'lease_type.in' =>
                'The selected lease type is invalid.',

            /*
            |--------------------------------------------------------------------------
            | Dates
            |--------------------------------------------------------------------------
            */

            'start_date.date' =>
                'The lease start date must be a valid date.',

            'end_date.date' =>
                'The lease end date must be a valid date.',

            'end_date.after_or_equal' =>
                'The lease end date must be on or after the start date.',

            /*
            |--------------------------------------------------------------------------
            | Financial Terms
            |--------------------------------------------------------------------------
            */

            'rent_amount.numeric' =>
                'The rent amount must be a valid number.',

            'rent_amount.min' =>
                'The rent amount cannot be negative.',

            'deposit_amount.numeric' =>
                'The deposit amount must be a valid number.',

            'deposit_amount.min' =>
                'The deposit amount cannot be negative.',

            'service_charge.numeric' =>
                'The service charge must be a valid number.',

            'service_charge.min' =>
                'The service charge cannot be negative.',

            'late_fee.numeric' =>
                'The late fee must be a valid number.',

            'late_fee.min' =>
                'The late fee cannot be negative.',

            /*
            |--------------------------------------------------------------------------
            | Payment Terms
            |--------------------------------------------------------------------------
            */

            'payment_frequency.in' =>
                'The selected payment frequency is invalid.',

            'due_day.between' =>
                'The due day must be between 1 and 31.',

            'notice_period_days.min' =>
                'The notice period cannot be negative.',

            'notice_period_days.max' =>
                'The notice period cannot exceed 365 days.',

            /*
            |--------------------------------------------------------------------------
            | Status
            |--------------------------------------------------------------------------
            */

            'status.in' =>
                'The selected lease status is invalid.',

            /*
            |--------------------------------------------------------------------------
            | Termination
            |--------------------------------------------------------------------------
            */

            'terminated_at.date' =>
                'The termination date must be a valid date.',

            'terminated_at.after_or_equal' =>
                'The termination date must be on or after the lease start date.',

            'termination_reason.max' =>
                'The termination reason cannot exceed 5,000 characters.',

            /*
            |--------------------------------------------------------------------------
            | Documents / Notes
            |--------------------------------------------------------------------------
            */

            'document_path.max' =>
                'The document path cannot exceed 500 characters.',

            'notes.max' =>
                'The notes cannot exceed 10,000 characters.',
        ];
    }

    /**
     * Get validated data prepared for the application layer.
     *
     * @return array<string, mixed>
     */
    public function validatedData(): array
    {
        return $this->validated();
    }
}